### ISSUE TITLE
R1 and R8 

### ISSUE THREAD

**Issue by 3xtr3m3d** [fmeschia/esr-meter#1]
Hi

Can you please give me the links to R1 and R8 you bought for this project?  

Regards

**Comment by fmeschia** [comment]
I just bought those resistors from a local supplier. But you can order them from digi-key, mouser or any other online store. R8 must be 1 Ohm with 1% accuracy. R8 is not critical in Ohm value, but it must be rated for at least 1 Watt.

**Comment by 3xtr3m3d** [comment]
thanks for the fast response. R1 wattage is not a problem?

**Comment by fmeschia** [comment]
The same current that goes through R8 also goes through R1. But R1 Ohmic value is less, so it “only” needs to be rated for at least 0.7 Watt. An example from Digi-Key is here: https://www.digikey.com/product-detail/en/ohmite/41F1R0E/41F1R0E-ND/823176

**Comment by 3xtr3m3d** [comment]
thanks a lot i will try that. im going to try your project as i'm testing some 18650 batteries.  

thanks a lot for posting this project on github

**Comment by allenchak** [comment]
Might I know which resistor is better for R1 & R8,

- 3W ±1% 1Ω
- 2W ±1% 1Ω
- 1W ±1% 1Ω
- 1W ±1% 0.1Ω
- 1W ±1% 0.68Ω

![2W-1R](https://user-images.githubusercontent.com/7300880/105282378-2ae39e80-5be9-11eb-8bdf-759ee4220694.jpg)

Moreover, in case I using ADS1115 as external ADC. Would it increase accuracy? Thank you for your reply.

**Comment by fmeschia** [comment]
I would go for a 1Ohm, 1%, 1W for R8. R1 doesn’t need to be rated for 1% precision, but it should be around 1.5Ohm and 2W.
I didn’t design this circuit to use and external ADC, I think it would need to be modified rather substantially.
