### ISSUE TITLE
Blank display

### ISSUE THREAD

**Issue by dickeos** [fmeschia/esr-meter#2]
Hello,

I finally got around to building your project (thank you), everything seemed to go ok with the build, I have managed to program the board using an FTDI controller I already had lying around using Arduino IDE and the Arduino Uno board profile. It said that the upload was successful so I have no reason to think it wasn't.

I just get a blank display, it lights up but nothing on there, I have tried powering the unit externally and its the same. I didn't use the exact 16x2 display but the pin configuration was the same as the one you have used.

Any ideas what I can try to diagnose?

**Comment by fmeschia** [comment]
I’d start by checking the voltage supplied to the panel. If the panel has backlighting, is it on? Does the LCD panel support 3.3V?
Next, I’d try to see if the microcontroller is working, by checking if the load is switched on and off. The measurement cycle is slow, so a multimeter should be enough.

**Comment by dickeos** [comment]
Great places to start troubleshhting, can you confirm the load is on pins 25&26?

**Comment by fmeschia** [comment]
Not exactly the load, but related to it. Pin 25 and 26 on the MCU read the voltages at the end of the precision 1Ohm current sense resistor, so you should see a voltage across them, from 0V to ~0.8V.

**Comment by dickeos** [comment]
Turns out if was some faulty ribbon cable! It appears to work now. One last question, the 8mhz crystal, does it have to be 8mhz or will a 16mhz one suffice?

**Comment by fmeschia** [comment]
8MHz is within the operating spec for the microcontroller when powered at 3.3V. 16MHz may be a bit too much for 3.3V, for that frequency 5V would be more “comfortable”.

**Comment by dickeos** [comment]
Thank you so much for all of your advice, the project is great and will be very useful for me.

**Comment by fmeschia** [comment]
Glad to hear that!
